"""Find gold chunks the eval set is missing, and add them after human review.

    python -m scripts.gold_audit propose            # writes eval/gold_review.jsonl
    # ... you edit the decision field in that file ...
    python -m scripts.gold_audit apply              # folds the keeps into questions.jsonl

**Why this exists.** ``gold_chunk_ids`` was written by hand from a handful of chunks. The
index has 874. Papers cite their predecessors and surveys describe everything, so the same
fact usually appears in several chunks - q013 is answered by the PlaNet paper *and* by the
model-based RL survey. Every unlabelled valid source makes a successful retrieval look
like a miss, so hit@5 is a floor rather than a measurement, and Stage 3's improvement
would be measured against noise.

**The model proposes; you dispose.** Nothing is written to ``questions.jsonl`` by
``propose``. It writes a review file with an empty ``decision`` field per row, and
``apply`` acts only on rows you marked ``keep``. This is not ceremony: the gold set is the
ground truth that every number in the project rests on, and ground truth generated by the
same family of model being evaluated is circular reasoning. A tool that auto-accepted
would be manufacturing agreement with itself.

**Alternatives only.** A candidate is proposed only when it is an alternative source for a
fact an existing gold chunk already covers, and it is added *into that chunk's group*.
Candidates that answer some *different* part of the question are reported but never
proposed: adding one as a new group would raise the recall denominator and change what the
question is asking for, which is a question-design decision, not a labelling fix.

**The candidate pool is every retriever that gets measured, not just the dense one.** The
first pass drew candidates from dense retrieval's top 10 alone, while every published
number comes from the hybrid. A chunk that BM25 ranks 2nd and dense does not rank at all
was therefore never even a candidate for labelling - and that is precisely the shape of
the defect the first pass left behind: a question scoring *correct* while its retrieval
scored a *miss*, because the chunk that answered it was never on any gold list. The pool
is now the union of dense, BM25 and the fused hybrid, each at `--top-k`, which is the set
of chunks any measured configuration can surface.

Auditing deeper than that changes no published metric. The metrics are @1 and @5; a
chunk nothing ranks in its top 10 cannot turn a measured miss into a hit at k=5. Depth
buys labels for configurations that do not exist yet, and every extra candidate is another
chance for the auditor to fabricate one.
"""

import argparse
import json
from pathlib import Path

from arxiv_rag.config import get_settings
from arxiv_rag.evaluation.metrics import flatten
from arxiv_rag.evaluation.quotes import quote_supported
from arxiv_rag.llm import chat
from arxiv_rag.retrieval.bm25 import BM25Index
from arxiv_rag.retrieval.hybrid import DenseRetriever, HybridRetriever
from arxiv_rag.retrieval.store import ChunkStore

ROOT = Path(__file__).resolve().parents[1]
QUESTIONS = ROOT / "eval" / "questions.jsonl"
REVIEW = ROOT / "eval" / "gold_review.jsonl"

MAX_CHARS = 900  # chunks are up to 800 tokens; the fact is almost always near the start

SYSTEM = """You audit the labels of a retrieval evaluation set for machine-learning papers.

You are given a QUESTION, its REFERENCE ANSWER, the GOLD passages already labelled as \
sources, and CANDIDATE passages that retrieval returned but nobody labelled.

The reference answer is the ground truth. The gold passages are an INCOMPLETE and \
possibly imperfect record of where its claims can be found - your job is to find the \
places that were missed.

For each candidate decide exactly one of:
- "alternative": on its own, this candidate supports a claim of the REFERENCE ANSWER that \
one of the gold passages also supports. Someone handed only this candidate could answer \
that part of the question. Name the gold passage covering the same claim.
- "other": it supports a DIFFERENT claim of the reference answer, or is on topic but \
supports no claim in it.
- "irrelevant": it has nothing to do with the reference answer.

What does NOT disqualify a candidate from being an "alternative":
- being from a different paper. A survey describing PlaNet, or the DreamerV2 paper \
describing what DreamerV1 did, is a perfectly good source. Papers restate their \
predecessors constantly, and those restatements are the labels most often missed.
- using different words, being shorter, or being less detailed than the gold passage.
- covering only part of the reference answer, as long as it fully covers the part the \
named gold passage covers.

What DOES disqualify it:
- merely alluding to the claim, citing it, or naming the system without stating the fact.
- stating the fact about a DIFFERENT system, or a different version of the same system \
(V-JEPA 2 is not V-JEPA; DreamerV3 is not DreamerV2). That is "other".

Reply with JSON only, one entry per candidate:
{"candidates": [{"id": "<candidate id>", "verdict": "alternative|other|irrelevant", \
"alternative_to": "<gold id, or empty>", "quote": "<the words in the candidate that state \
the claim, or empty>"}]}"""


def clean_id(raw: str) -> str:
    """Strip anything the model may have glued onto a chunk id.

    The passage headers read ``CANDIDATE 2107.08241::17 | title``, and a model echoing
    the id sometimes brings the label or the title along. An id that does not match a
    real chunk is silently dropped, so normalise before rejecting.
    """
    text = (raw or "").strip()
    for prefix in ("CANDIDATE ", "GOLD ", "candidate ", "gold "):
        if text.startswith(prefix):
            text = text[len(prefix) :]
    return text.split("|")[0].strip()


def load_questions() -> list[dict]:
    return [json.loads(line) for line in QUESTIONS.read_text().splitlines() if line.strip()]


def passage_block(label: str, chunks: list) -> str:
    parts = []
    for c in chunks:
        head = f"{label} {c.chunk_id} | {c.title}"
        if c.section:
            head += f" | {c.section}"
        parts.append(f"{head}\n{c.text[:MAX_CHARS]}")
    return "\n\n".join(parts)


def propose(args) -> None:
    settings = get_settings()
    store = ChunkStore.load(settings.index_dir)
    by_id = {c.chunk_id: c for c in store.chunks}

    # The three retrievers whose numbers appear in docs/results.md, configured exactly as
    # they are there. Fusion depth has to be at least the pool depth or the fused list is
    # shorter than what is being asked for.
    dense = DenseRetriever(store, settings)
    bm25 = BM25Index(store.chunks)
    hybrid = HybridRetriever(
        [dense, bm25],
        depth=max(settings.fusion_depth, args.top_k),
        rrf_k=settings.rrf_k,
        weights=settings.fusion_weight_list,
    )
    pools = {"hybrid": hybrid, "dense": dense, "bm25": bm25}

    questions = [q for q in load_questions() if q["answerable"]]
    if args.only:
        questions = [q for q in questions if q["id"] == args.only]
    questions = questions[: args.limit]

    rows: list[dict] = []
    REVIEW.write_text("")
    print(
        f"auditing {len(questions)} questions; candidates = top-{args.top_k} of "
        f"{', '.join(pools)}, unioned\n"
    )

    for i, q in enumerate(questions, start=1):
        gold_ids = flatten(q["gold_chunk_ids"])
        # One rank table per retriever, and the candidate list ordered by the hybrid's
        # view - it is the one that ships, so a reviewer reading top to bottom sees the
        # proposals that can actually move a number first.
        ranks = {
            name: {
                h.chunk.chunk_id: r
                for r, h in enumerate(pool.search(q["question"], k=args.top_k), start=1)
            }
            for name, pool in pools.items()
        }
        found = {cid: by_id[cid] for table in ranks.values() for cid in table if cid in by_id}
        candidates = sorted(
            (c for cid, c in found.items() if cid not in gold_ids),
            key=lambda c: ranks["hybrid"].get(c.chunk_id, 999),
        )
        if not candidates:
            print(f"{i:3}/{len(questions)}  {q['id']}  no unlabelled candidates")
            continue

        gold_block = passage_block("GOLD", [by_id[g] for g in gold_ids if g in by_id])
        user = (
            f"QUESTION:\n{q['question']}\n\n"
            f"REFERENCE ANSWER:\n{q['reference_answer']}\n\n"
            f"GOLD PASSAGES:\n{gold_block}\n\n"
            f"CANDIDATE PASSAGES:\n{passage_block('CANDIDATE', candidates)}"
        )
        response = chat(
            settings,
            model=settings.judge_model,
            messages=[{"role": "system", "content": SYSTEM}, {"role": "user", "content": user}],
            temperature=0,
            response_format={"type": "json_object"},
        )
        if args.debug:
            print(f"\n--- {q['id']} candidates sent ---")
            for c in candidates:
                where = " ".join(
                    f"{name[0]}{table[c.chunk_id]}"
                    for name, table in ranks.items()
                    if c.chunk_id in table
                )
                print(f"  {c.chunk_id}  ({where})  {c.title[:60]}")
            print(f"--- raw reply ---\n{response.choices[0].message.content}\n")
        try:
            verdicts = json.loads(response.choices[0].message.content or "{}").get("candidates", [])
        except json.JSONDecodeError:
            print(f"{i:3}/{len(questions)}  {q['id']}  unparseable reply, skipped")
            continue

        proposed = others = 0
        unmatched: list[str] = []
        unsupported: list[tuple[str, str]] = []
        for v in verdicts:
            verdict = v.get("verdict")
            if verdict not in ("alternative", "other"):
                continue
            cid, target = clean_id(v.get("id", "")), clean_id(v.get("alternative_to", ""))
            if cid not in by_id:
                # An id matching no chunk cannot be acted on - but say so. Dropping
                # these in silence is what made four questions look like clean passes
                # when the model had answered and the parser rejected it.
                unmatched.append(v.get("id", ""))
                continue
            quote = v.get("quote", "")
            # The model fabricated quotes on this exact task: fluent, on topic, and
            # absent from the chunk named. An alternative must point at words that are
            # really there, or it is not evidence of anything.
            if verdict == "alternative" and not quote_supported(quote, by_id[cid].text):
                unsupported.append((cid, quote[:60]))
                verdict = "other"
            is_alt = verdict == "alternative" and target in gold_ids
            rows.append(
                {
                    # alternatives are yours to decide; "other" rows are pre-marked drop
                    # so they do not block `apply`, but they are written out anyway - a
                    # false negative you cannot see is a false negative you cannot fix.
                    "decision": "" if is_alt else "drop",
                    "verdict": verdict,
                    "question_id": q["id"],
                    "question": q["question"],
                    "candidate_id": cid,
                    # The rank that matters is the shipped retriever's. The other two
                    # are kept because "dense never saw it" is the interesting case.
                    "candidate_rank": ranks["hybrid"].get(cid),
                    "rank_dense": ranks["dense"].get(cid),
                    "rank_bm25": ranks["bm25"].get(cid),
                    "alternative_to": target if is_alt else "",
                    "quote": quote[:300],
                    "candidate_title": by_id[cid].title,
                    "candidate_text": by_id[cid].text[:MAX_CHARS],
                }
            )
            proposed += is_alt
            others += not is_alt
        warn = f"  !! {len(unmatched)} unmatched ids: {unmatched[:2]}" if unmatched else ""
        if unsupported:
            warn += f"  !! {len(unsupported)} fabricated quotes rejected"
        print(f"{i:3}/{len(questions)}  {q['id']}  {proposed} proposed, {others} other{warn}")

    with REVIEW.open("w") as fh:
        for row in rows:
            fh.write(json.dumps(row, ensure_ascii=False) + "\n")

    alts = [r for r in rows if r["decision"] == ""]
    print(
        f"\n{len(rows)} rows -> {REVIEW.relative_to(ROOT)}  "
        f"({len(alts)} proposed as alternatives, {len(rows) - len(alts)} pre-marked drop)"
    )
    print(
        'Set "decision" to "keep" or "drop" on each row, then run: '
        "python -m scripts.gold_audit apply"
    )
    if not alts:
        print(
            "\n  nothing proposed. Scan the pre-marked rows in the review file before "
            "concluding the labels are complete."
        )
    for row in alts:
        print(
            f"\n  {row['question_id']}  +{row['candidate_id']} (rank {row['candidate_rank']}) "
            f"-> into the group holding {row['alternative_to']}"
        )
        print(f"    Q: {row['question'][:88]}")
        print(f"    quote: {row['quote'][:140]}")


def apply(args) -> None:
    if not REVIEW.exists():
        raise SystemExit("no eval/gold_review.jsonl - run `propose` first")
    rows = [json.loads(line) for line in REVIEW.read_text().splitlines() if line.strip()]
    keeps = [r for r in rows if r["decision"].strip().lower() == "keep"]
    undecided = [r for r in rows if not r["decision"].strip()]
    if undecided:
        raise SystemExit(
            f"{len(undecided)} rows still have an empty decision "
            f"({', '.join(r['question_id'] for r in undecided[:5])}...). "
            "Mark every row keep or drop - an unreviewed label is not a label."
        )

    questions = load_questions()
    by_qid = {q["id"]: q for q in questions}
    added = 0
    for r in keeps:
        q = by_qid.get(r["question_id"])
        if q is None:
            continue
        for group in q["gold_chunk_ids"]:
            if r["alternative_to"] in group and r["candidate_id"] not in group:
                group.append(r["candidate_id"])
                added += 1
                break

    with QUESTIONS.open("w") as fh:
        for q in questions:
            fh.write(json.dumps(q, ensure_ascii=False) + "\n")
    print(f"kept {len(keeps)} of {len(rows)} proposals, added {added} chunks into existing groups")
    print("now run: make check-eval && make eval")


def main() -> None:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="command", required=True)
    p = sub.add_parser("propose", help="ask the model which unlabelled chunks also answer")
    p.add_argument(
        "--top-k", type=int, default=10, help="depth per retriever; the pools are unioned"
    )
    p.add_argument("--limit", type=int, default=None)
    p.add_argument("--only", default=None, help="audit a single question id, e.g. q013")
    p.add_argument("--debug", action="store_true", help="print candidates and the raw reply")
    p.set_defaults(func=propose)
    a = sub.add_parser("apply", help="fold the rows you marked 'keep' into questions.jsonl")
    a.set_defaults(func=apply)
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
